import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  loadingContainer: { flex: 1, backgroundColor: '#0f0f13', justifyContent: 'center', alignItems: 'center' },
  container: { flex: 1, backgroundColor: '#0f0f13' },
  scrollContent: { padding: 20, gap: 20 },
  headerSection: { marginBottom: 8, marginTop: 10 },
  pageTitle: { color: '#93c5fd', fontSize: 22, fontWeight: '900', letterSpacing: 1 },
  leagueNameRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 6 },
  leagueName: { color: '#f59e0b', fontSize: 14, fontWeight: '600' },
  card: { backgroundColor: '#18181b', borderWidth: 1, borderColor: '#27272a', borderRadius: 16, padding: 20 },
  cardHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 16 },
  cardTitle: { color: '#fff', fontSize: 18, fontWeight: '700' },
  cardDesc: { color: '#a1a1aa', fontSize: 14, lineHeight: 22 },
  blankStateCard: { backgroundColor: '#18181b', borderWidth: 1, borderColor: '#27272a', borderRadius: 16, padding: 30, alignItems: 'center', textAlign: 'center' },
  preSeasonCard: { backgroundColor: '#18181b', borderWidth: 1, borderColor: '#f59e0b', borderRadius: 16, padding: 20 },
  startDateText: { color: '#fff', fontSize: 20, fontWeight: 'bold', marginBottom: 12 },

  // Match Hub Logic
  versusContainer: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 16, marginVertical: 20, backgroundColor: '#121215', paddingVertical: 24, borderRadius: 12, borderWidth: 1, borderColor: '#27272a' },
  teamText: { color: '#fff', fontSize: 20, fontWeight: '900', flex: 1, textAlign: 'center' },
  vsText: { color: '#71717a', fontSize: 16, fontWeight: 'bold' },
  deadlineText: { color: '#a1a1aa', fontSize: 13, textAlign: 'center', marginBottom: 20 },
  syncButton: { flexDirection: 'row', backgroundColor: '#f59e0b', paddingVertical: 16, borderRadius: 12, alignItems: 'center', justifyContent: 'center', gap: 8 },
  syncButtonText: { color: '#000', fontSize: 16, fontWeight: 'bold' },
  waitingBox: { padding: 14, backgroundColor: '#1f1f25', borderRadius: 12, alignItems: 'center', borderWidth: 1, borderColor: '#27272a' },
  waitingText: { color: '#a1a1aa', fontSize: 14, fontWeight: '600' },
  gameCodeBox: { padding: 12, backgroundColor: 'rgba(56, 189, 248, 0.1)', borderColor: '#38bdf8', borderWidth: 1, borderRadius: 12, alignItems: 'center', marginBottom: 12 },
  gameCodeLabel: { color: '#38bdf8', fontSize: 11, fontWeight: 'bold', marginBottom: 4 },
  gameCodeVal: { color: '#fff', fontSize: 20, fontWeight: '900', letterSpacing: 2 },

  // Completed Scorecard
  completedScoreContainer: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginVertical: 20, backgroundColor: '#121215', paddingVertical: 24, borderRadius: 12, borderWidth: 1, borderColor: '#27272a' },
  teamCol: { flex: 1, alignItems: 'center', gap: 8 },
  teamNameText: { color: '#a1a1aa', fontSize: 12, fontWeight: 'bold', letterSpacing: 1 },
  scoreBigText: { fontSize: 40, fontWeight: '900' },
  ftCol: { paddingHorizontal: 16, alignItems: 'center' },
  ftBadge: { color: '#71717a', fontSize: 14, fontWeight: '900', backgroundColor: '#1f1f25', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  completedBadgeBox: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: 'rgba(16, 185, 129, 0.1)', padding: 16, borderRadius: 12, borderWidth: 1, borderColor: '#10b981' },
  completedBadgeText: { color: '#10b981', fontSize: 14, fontWeight: 'bold' },

  // Time Picker UI
  adjournContainer: { marginTop: 10 },
  adjournHelp: { color: '#a1a1aa', fontSize: 12, textAlign: 'center', marginBottom: 12 },
  adjournRow: { flexDirection: 'row', gap: 12 },
  timeSelectBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#121215', borderWidth: 1, borderColor: '#27272a', borderRadius: 10, paddingVertical: 12, gap: 8 },
  timeSelectText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  proposeBtn: { flex: 1, backgroundColor: '#334155', borderRadius: 10, justifyContent: 'center', alignItems: 'center' },
  proposeBtnText: { color: '#fff', fontSize: 14, fontWeight: 'bold' },
  proposedBox: { flexDirection: 'column', gap: 16, backgroundColor: '#1f1f25', padding: 16, borderRadius: 12, borderWidth: 1, borderColor: '#f59e0b', alignItems: 'center', marginTop: 8 },
  proposedText: { color: '#d4d4d8', fontSize: 15, fontWeight: '600' },
  proposedTimeHighlight: { color: '#fff', fontSize: 18, fontWeight: '900', letterSpacing: 1 },
  waitingBadge: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: 'rgba(245, 158, 11, 0.15)', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 8 },
  waitingOpponentText: { color: '#f59e0b', fontSize: 13, fontWeight: 'bold' },
  acceptBtn: { backgroundColor: '#10b981', paddingVertical: 12, paddingHorizontal: 20, borderRadius: 10, width: '100%', alignItems: 'center' },
  acceptBtnText: { color: '#fff', fontWeight: '900', fontSize: 15, letterSpacing: 1 },

  // Ladder Table
  ladderContainer: { backgroundColor: '#18181b', borderWidth: 1, borderColor: '#27272a', borderRadius: 16, overflow: 'hidden' },
  cardHeaderRowPad: { flexDirection: 'row', alignItems: 'center', gap: 8, padding: 20, paddingBottom: 16 },
  tableWrapper: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: '#27272a' },
  fixedLeftCol: { width: 140, borderRightWidth: 1, borderRightColor: '#27272a', backgroundColor: '#18181b' },
  scrollingRightCol: { backgroundColor: '#18181b' },
  tableHeaderRow: { flexDirection: 'row', alignItems: 'center', height: 40, borderBottomWidth: 1, borderBottomColor: '#27272a', backgroundColor: '#1f1f25' },
  tableHeaderText: { color: '#71717a', fontSize: 11, fontWeight: 'bold' },
  statHeaderCell: { color: '#71717a', fontSize: 11, fontWeight: 'bold', width: 45, textAlign: 'center' },
  tableDataRow: { flexDirection: 'row', alignItems: 'center', height: 48, borderBottomWidth: 1, borderBottomColor: '#27272a' },
  highlightRow: { backgroundColor: 'rgba(245, 158, 11, 0.1)', borderLeftWidth: 3, borderLeftColor: '#f59e0b' },
  rankText: { color: '#a1a1aa', fontSize: 13, fontWeight: 'bold', width: 30, textAlign: 'center' },
  clubText: { color: '#d4d4d8', fontSize: 14, fontWeight: '500', flex: 1, paddingRight: 8 },
  statCell: { color: '#d4d4d8', fontSize: 13, width: 45, textAlign: 'center' },

  // Dual Column Picker UI
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.85)', justifyContent: 'center', alignItems: 'center' },
  pickerBox: { backgroundColor: '#18181b', width: 300, height: 350, borderRadius: 16, borderWidth: 1, borderColor: '#27272a', overflow: 'hidden', flexDirection: 'column' },
  pickerHeader: { backgroundColor: '#27272a', padding: 16, alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#333' },
  pickerTitle: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
  pickerColumnsContainer: { flexDirection: 'row', flex: 1, height: 200 },
  pickerColumn: { flex: 1 },
  pickerDivider: { justifyContent: 'center', alignItems: 'center' },
  timeOption: { paddingVertical: 14, alignItems: 'center' },
  timeOptionText: { color: '#71717a', fontSize: 20, fontWeight: '500' },
  activeTimeText: { color: '#f59e0b', fontWeight: '900', fontSize: 24 },
  pickerActions: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: '#333' },
  closePickerBtn: { flex: 1, backgroundColor: '#222225', padding: 16, alignItems: 'center', borderRightWidth: 1, borderRightColor: '#333' },
  closePickerText: { color: '#ef4444', fontWeight: 'bold', fontSize: 16 },
  confirmPickerBtn: { flex: 1, backgroundColor: '#f59e0b', padding: 16, alignItems: 'center' },
  confirmPickerText: { color: '#000', fontWeight: 'bold', fontSize: 16 }
});
